name: Fetch and Upload Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIA34AMCXKIOIK43F4N }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.0c8BRq1bDwbH5a27m8vQWnsDKb1avf7FCBPsKBc4 }}
      run: |
        aws s3 cp data.xlsx s3://your-bucket-name/all_odds.xlsx
